apiVersion: v1
kind: Service
metadata:
  name: ollama-hologram-chatbot
  namespace: demos-main
spec:
  selector:
    app: ollama-hologram-chatbot
  ports:
  - name: didcomm
    port: 3001
    targetPort: 3001
    protocol: TCP
  - name: admin
    port: 4000
    targetPort: 4000
    protocol: TCP
  - name: q
    port: 2903
    targetPort: 2903
    protocol: TCP
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  